[versions]
kotlin = "2.0.21"
junit = "5.11.3"
xmlunit = "2.9.0"
commons-text = "1.12.0"

[libraries]
xmlunit-matchers = { module = "org.xmlunit:xmlunit-matchers", version.ref = "xmlunit" }

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }