[versions]
kotlin = "2.0.21"
junit = "5.11.3"
xmlunit = "2.9.0"
commons-text = "1.12.0"

[libraries]

kotlin-gradle-plugin = { group = "org.jetbrains.kotlin",name = "kotlin-gradle-plugin", version.ref = "kotlin" }

