/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}
gradle.startParameter.isBuildCacheEnabled = true
gradle.startParameter.isBuildScan = true

tasks.register("cleanBuildCache", Delete::class) {
    doLast {
        layout.buildDirectory.get().asFile.deleteRecursively()
        println("Build cache cleaned!")
    }
}


dependencies {
    implementation("org.apache.commons:commons-text:1.12.0")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.0.20")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.10.3")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
