name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up the Java environment (JDK 11 or any required version)
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      # Make the gradlew file executable
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      # Build the project using Gradle Wrapper
      - name: Build with Gradle
        run: ./gradlew build
