name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Only one checkout is needed

      # Set up the Java environment (JDK 21 with Temurin)
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Supported distributions: 'zulu', 'temurin', etc.
          java-version: '21'

      # Build the project using Gradle wrapper
      - name: Build with Gradle
        run: ./gradlew build  # Use ./gradlew, not ./grad
